language: python
install:
  - curl -sSf https://gitlinks.github.io/cl-bins/install.sh | sh
  - pip install tox
after_success: "~/.gitlinks/hermes-rust-ci"
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py34
script:
- tox
